name: Pull request

on: [pull_request]

jobs:
  Build:
    name: Build & Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Run tests
        run: ./gradlew test assembleDebug
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
  Check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Code checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v2.2.4
        if: ${{ always() }}
        with:
          name: MQTT-Lint-report
          path: ./**/build/reports/lint-results.html
